[package]
name = "application"
version.workspace = true
edition.workspace = true

[dependencies]
domain = { path = "../domain" }
infrastructure = { path = "../infrastructure" }

async-trait = { workspace = true }

[features]
default = []

[lints]
workspace = true
